
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Kevstrosky\Documents\Ingenieria en Sistemas\git\Calidad 1\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    30.0,
    34.0,
    anchor="nw",
    text="Estación | Cerro de la Campana",
    fill="#666666",
    font=("MontserratRoman SemiBold", 16 * -1)
)

canvas.create_text(
    1000.0,
    34.0,
    anchor="nw",
    text="12:50 p.m. | Martes 28 de marzo del 2023 ",
    fill="#666666",
    font=("MontserratRoman SemiBold", 16 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    683.0,
    323.0,
    image=image_image_1
)

canvas.create_text(
    485.0,
    20.0,
    anchor="nw",
    text="Sonora Cycle",
    fill="#2192FF",
    font=("MontserratRoman Medium", 50 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=537.0,
    y=608.0,
    width=292.0,
    height=47.0
)

canvas.create_rectangle(
    67.0,
    170.0,
    310.0,
    218.0,
    fill="#E2F0FF",
    outline="")

canvas.create_text(
    114.0,
    182.0,
    anchor="nw",
    text="5 unidades",
    fill="#2192FF",
    font=("MontserratRoman Medium", 20 * -1)
)

canvas.create_text(
    67.0,
    142.0,
    anchor="nw",
    text="Bicicletas disponibles",
    fill="#666666",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    67.0,
    227.0,
    anchor="nw",
    text="Tiempo de renta",
    fill="#666666",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    67.0,
    313.0,
    anchor="nw",
    text="Precio de renta",
    fill="#666666",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    67.0,
    405.0,
    anchor="nw",
    text="Estacionamientos disponibles",
    fill="#666666",
    font=("MontserratRoman Medium", 16 * -1)
)

canvas.create_text(
    30.0,
    672.0,
    anchor="nw",
    text="Gestión de Calidad del Software I 2023-1 ",
    fill="#999999",
    font=("MontserratRoman Medium", 12 * -1)
)

canvas.create_rectangle(
    67.0,
    433.0,
    310.0,
    481.0,
    fill="#E2F0FF",
    outline="")

canvas.create_text(
    114.0,
    445.0,
    anchor="nw",
    text="2 espacios",
    fill="#2192FF",
    font=("MontserratRoman Medium", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    92.0,
    457.0,
    image=image_image_2
)

canvas.create_rectangle(
    64.0,
    256.0,
    310.0,
    304.0,
    fill="#E2F0FF",
    outline="")

canvas.create_text(
    114.0,
    268.0,
    anchor="nw",
    text="2 horas",
    fill="#2192FF",
    font=("MontserratRoman Medium", 20 * -1)
)

canvas.create_rectangle(
    64.0,
    342.0,
    310.0,
    390.0,
    fill="#E2F0FF",
    outline="")

canvas.create_text(
    114.0,
    354.0,
    anchor="nw",
    text="20 MXN",
    fill="#2192FF",
    font=("MontserratRoman Medium", 20 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1159.0,
    509.0,
    image=image_image_3
)

canvas.create_text(
    1090.0,
    672.0,
    anchor="nw",
    text="Desarrollado por Kevin Ochoa Guerrero",
    fill="#999999",
    font=("MontserratRoman Medium", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    92.0,
    366.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    92.0,
    280.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    92.0,
    194.0,
    image=image_image_6
)

canvas.create_rectangle(
    1090.0,
    170.0,
    1333.0,
    481.0,
    fill="#E2F0FF",
    outline="")

canvas.create_text(
    1090.0,
    142.0,
    anchor="nw",
    text="¿Cómo rentar?",
    fill="#2192FF",
    font=("MontserratRoman SemiBold", 16 * -1)
)

canvas.create_text(
    1099.0,
    213.0,
    anchor="nw",
    text="1.- Descarga nuestra aplicación\n2.- Registrate en la aplicación\n3.- Pulsa en esta pantalla el botón \n     RENTAR \n4.- Escanea el Código QR en la \n      aplicación \n5.- Selecciona una de las bicicletas\n6.- Escoge el método de pago de\n      preferencia. (Tarjeta de crédito y/o\n      efectivo)\n7.- ¡Y eso es todo! Recuerda dejar la\n     la bicicleta en cualquier estación\n     disponible.\n",
    fill="#333333",
    font=("MontserratRoman Medium", 12 * -1)
)

canvas.create_text(
    1099.0,
    189.0,
    anchor="nw",
    text="Sólo en sigue estos 7 pasos",
    fill="#2192FF",
    font=("MontserratRoman Medium", 14 * -1)
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1277.0,
    509.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    844.0,
    50.0,
    image=image_image_8
)
window.resizable(False, False)
window.mainloop()
