
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Kevstrosky\Documents\Ingenieria en Sistemas\git\Calidad 1\frame2\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1366x720")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 720,
    width = 1366,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    33.0,
    34.0,
    anchor="nw",
    text="Estación | Cerro de la Campana",
    fill="#666666",
    font=("MontserratRoman SemiBold", 16 * -1)
)

canvas.create_text(
    1003.0,
    34.0,
    anchor="nw",
    text="12:50 p.m. | Martes 28 de marzo del 2023 ",
    fill="#666666",
    font=("MontserratRoman SemiBold", 16 * -1)
)

canvas.create_text(
    488.0,
    20.0,
    anchor="nw",
    text="Sonora Cycle",
    fill="#2192FF",
    font=("MontserratRoman Medium", 50 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    683.0,
    360.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    847.0,
    50.0,
    image=image_image_2
)

canvas.create_text(
    371.0,
    532.0,
    anchor="nw",
    text="Por favor, escanea este código QR en tu aplicación",
    fill="#666666",
    font=("MontserratRoman SemiBold", 24 * -1)
)
window.resizable(False, False)
window.mainloop()
